vim.pack.add({ "https://github.com/nvim-mini/mini.nvim" })

-- local window_config = function()
--   local height = math.floor(0.618 * vim.o.lines)
--   local width = math.floor(0.618 * vim.o.columns)
--   return {
--     anchor = 'NW',
--     height = height,
--     width = width,
--     row = math.floor(0.5 * (vim.o.lines - height)),
--     col = math.floor(0.5 * (vim.o.columns - width)),
--   }
-- end
--
-- -- text editing
-- require('mini.ai').setup()
-- require('mini.move').setup()
-- require('mini.pairs').setup()
-- require('mini.surround').setup()
--
-- -- general
-- require('mini.git').setup()
-- require('mini.diff').setup()
-- require('mini.pick').setup({
--   window = { config = window_config }
-- })
-- require('mini.files').setup()
-- require('mini.extra').setup()
--
-- -- appearance
-- require('mini.icons').setup()
-- require('mini.statusline').setup()
